// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbvAip7Ezqt7J18qlTH7-3rezo5Bg5SOw',
    appId: '1:533986648017:web:7fbe77e80d90bb93488af0',
    messagingSenderId: '533986648017',
    projectId: 'jobportal-b7092',
    authDomain: 'jobportal-b7092.firebaseapp.com',
    storageBucket: 'jobportal-b7092.firebasestorage.app',
    measurementId: 'G-JLCWQ8DD9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdoXo1bRC1orprJ-_E04eMw2Mvzgxoy9s',
    appId: '1:533986648017:android:c59552709a7100d8488af0',
    messagingSenderId: '533986648017',
    projectId: 'jobportal-b7092',
    storageBucket: 'jobportal-b7092.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2cAwvIA0jPrTo-L4nrjqKB5jZyJe-U8M',
    appId: '1:533986648017:ios:a82ce3e4357b450e488af0',
    messagingSenderId: '533986648017',
    projectId: 'jobportal-b7092',
    storageBucket: 'jobportal-b7092.firebasestorage.app',
    iosBundleId: 'com.example.jobApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2cAwvIA0jPrTo-L4nrjqKB5jZyJe-U8M',
    appId: '1:533986648017:ios:a82ce3e4357b450e488af0',
    messagingSenderId: '533986648017',
    projectId: 'jobportal-b7092',
    storageBucket: 'jobportal-b7092.firebasestorage.app',
    iosBundleId: 'com.example.jobApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbvAip7Ezqt7J18qlTH7-3rezo5Bg5SOw',
    appId: '1:533986648017:web:e753f40208f2576c488af0',
    messagingSenderId: '533986648017',
    projectId: 'jobportal-b7092',
    authDomain: 'jobportal-b7092.firebaseapp.com',
    storageBucket: 'jobportal-b7092.firebasestorage.app',
    measurementId: 'G-8SVJCG2YY7',
  );
}
